name: Auto Delete Snapshots
version: 0.0.1
slug: autodelete
description: Container to automatically delete backups older than set number of days
url: https://github.com/tomikaa87/hassio-backup-azure-blob/tree/main/autodelete
startup: once
boot: manual
image: ghcr.io/tomikaa87/{arch}-ha-addon-autodelete
init: false
options:
  daystokeep: 7
schema:
  daystokeep: int(1,)
map:
  - backup:rw
arch:
  - aarch64
stage: experimental
